// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePortfolio(arg1) {
  return window['go']['controller']['PortfoliosController']['DeletePortfolio'](arg1);
}

export function GetPortfolios() {
  return window['go']['controller']['PortfoliosController']['GetPortfolios']();
}

export function InsertPortfolio(arg1) {
  return window['go']['controller']['PortfoliosController']['InsertPortfolio'](arg1);
}

export function UpdatePortfolio(arg1) {
  return window['go']['controller']['PortfoliosController']['UpdatePortfolio'](arg1);
}
