// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function DeletePortfolio(arg1:number):Promise<boolean>;

export function GetPortfolios():Promise<Array<entities.Portfolio>>;

export function InsertPortfolio(arg1:string):Promise<void>;

export function UpdatePortfolio(arg1:entities.Portfolio):Promise<boolean>;
