// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';

export function GetBonds():Promise<Array<entities.Bond>>;

export function InsertBond(arg1:entities.Bond):Promise<void>;
