// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteBond(arg1) {
  return window['go']['bonds']['BondsController']['DeleteBond'](arg1);
}

export function GetBonds() {
  return window['go']['bonds']['BondsController']['GetBonds']();
}

export function InsertBond(arg1) {
  return window['go']['bonds']['BondsController']['InsertBond'](arg1);
}

export function UpdateBond(arg1) {
  return window['go']['bonds']['BondsController']['UpdateBond'](arg1);
}
