import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../css/custom-scroll.css";
import Header from "@/widgets/header";
import { AlertsProvider } from "@/features/alerts/AlertsProvider";
import ThemeProviders from "@/features/theme/ThemeProvider";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&family=Noto+Sans+JP:wght@100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased hide-scroll`}>
        <ThemeProviders>
          <div className="min-h-screen bg-gradient-to-br from-[#070521] to-black glass:to-background">
            {/* <Background /> */}
            <Header />
            <AlertsProvider>
              <div className="padx h-full overflow-hidden">{children}</div>
            </AlertsProvider>
          </div>
        </ThemeProviders>
      </body>
    </html>
  );
}
